apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

patches:
- patch: |-
    - op: replace
      path: "/metadata/labels/env"
      value: "prod"
  target:
    labelSelector: "env=OVERLAY"

