
# Application logging
logging:
  charset:
    console: utf-8
  level:
    root: INFO
    org:
      springframework=INFO: INFO


# Profile "dev"
reactor:
  netty:
    pool:
      maxConnections: 500

spring:
  main:
    banner-mode: console
  profiles:
    active: dev
    include: dev
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESQL_HOST:192.168.64.3}:${POSTGRESQL_PORT:30432}/postgres
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null
  liquibase:
    # Liquibase uses JDBC drive
    url: jdbc:postgresql://${POSTGRESQL_HOST:192.168.64.3}:${POSTGRESQL_PORT:30432}/postgres
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres

server:
  port: 8080

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
---
# Profile "prod"
