
# Application logging
logging:
  charset:
    console: utf-8
  level:
    root: INFO
    org:
      springframework=INFO: INFO


# Profile "dev"
reactor:
  netty:
    pool:
      maxConnections: 500

spring:
  main:
    banner-mode: console
  profiles:
    active: dev
    include: dev
  r2dbc:
    url: r2dbc:postgresql://postgres:postgres@localhost:5432/postgres
    initialization-mode: alawys
  sql:
    init:
      data-locations: classpath*:db/postgres/data.sql
      schema-locations: classpath*:db/postgres/schema.sql
  data:
    mongodb:
      uri: mongodb://localhost:27017/dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
---
# Profile "prod"
