apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
      volumes:
        - name: postgres-data-storage
          persistentVolumeClaim:
            claimName: postgres-volume-claim