apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hr-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - hr-gateway
  http:
    - match:
        - uri:
            prefix: /hrservice
      route:
        - destination:
            host: hrservice.hr.svc.cluster.local
            port:
              number: 9080