apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrservice
  labels:
    env: OVERLAY
spec:
  selector:
    matchLabels:
      app: hrservice
  replicas: 1
  template:
    metadata:
      labels:
        app: hrservice
    spec:
      containers:
        - name: hrservice
          image: localhost:32000/hrservice
          ports:
            - containerPort: 9080
              name: "http"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: $(POSTGRES_SERVICE_SERVICE_HOST)
            - name: POSTGRES_PORT
              value: "5432"
          resources:
            limits:
              memory: 512Mi
              cpu: "250m"