apiVersion: v1
kind: Service
metadata:
  name: hrservice
  labels:
    env: OVERLAY
spec:
  type: NodePort
  selector:
    app: hrservice
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080