#
# 1. docker-compose up
# 2. docker exec -it <docker-container-id> bash
# 3. psql -U petclinic
#
version: "3.5"

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql

  mongodb:
      image: mongo
      container_name: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
        ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
        ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
