apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    env: OVERLAY
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432