apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    env: OVERLAY
    type: local
spec:
  claimRef:
    namespace: hr
    name: postgres-volume-claim
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/yangwang/development/storage/postgres"