apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    env: OVERLAY
spec:
  volumeName: postgres-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi