apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hrservice

namespace: hr

resources:
  - ./namespace.yaml
  - db/postgres-pv.yaml
  - db/postgres-pvc.yaml
  - db/postgres-deployment.yaml
  - db/postgres-service.yaml
  - hr/hr-deployment.yaml
  - hr/hr-service.yaml
  - book-info/bookinfo.yaml
  - book-info/bookinfo-gateway.yaml

configMapGenerator:
  - name: postgres-config
    literals:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres